(function($) {
    $(document).ready(function() {
	
	$('#montecarlo').scianimator({
	    'images': ['images/montecarlo/montecarlo1.png', 'images/montecarlo/montecarlo2.png', 'images/montecarlo/montecarlo3.png', 'images/montecarlo/montecarlo4.png', 'images/montecarlo/montecarlo5.png', 'images/montecarlo/montecarlo6.png', 'images/montecarlo/montecarlo7.png', 'images/montecarlo/montecarlo8.png', 'images/montecarlo/montecarlo9.png', 'images/montecarlo/montecarlo10.png', 'images/montecarlo/montecarlo11.png', 'images/montecarlo/montecarlo12.png', 'images/montecarlo/montecarlo13.png', 'images/montecarlo/montecarlo14.png', 'images/montecarlo/montecarlo15.png', 'images/montecarlo/montecarlo16.png', 'images/montecarlo/montecarlo17.png', 'images/montecarlo/montecarlo18.png', 'images/montecarlo/montecarlo19.png', 'images/montecarlo/montecarlo20.png', 'images/montecarlo/montecarlo21.png', 'images/montecarlo/montecarlo22.png', 'images/montecarlo/montecarlo23.png', 'images/montecarlo/montecarlo24.png', 'images/montecarlo/montecarlo25.png', 'images/montecarlo/montecarlo26.png', 'images/montecarlo/montecarlo27.png', 'images/montecarlo/montecarlo28.png', 'images/montecarlo/montecarlo29.png', 'images/montecarlo/montecarlo30.png', 'images/montecarlo/montecarlo31.png', 'images/montecarlo/montecarlo32.png', 'images/montecarlo/montecarlo33.png', 'images/montecarlo/montecarlo34.png', 'images/montecarlo/montecarlo35.png', 'images/montecarlo/montecarlo36.png', 'images/montecarlo/montecarlo37.png', 'images/montecarlo/montecarlo38.png', 'images/montecarlo/montecarlo39.png', 'images/montecarlo/montecarlo40.png', 'images/montecarlo/montecarlo41.png', 'images/montecarlo/montecarlo42.png', 'images/montecarlo/montecarlo43.png', 'images/montecarlo/montecarlo44.png', 'images/montecarlo/montecarlo45.png', 'images/montecarlo/montecarlo46.png', 'images/montecarlo/montecarlo47.png', 'images/montecarlo/montecarlo48.png', 'images/montecarlo/montecarlo49.png', 'images/montecarlo/montecarlo50.png', 'images/montecarlo/montecarlo51.png', 'images/montecarlo/montecarlo52.png', 'images/montecarlo/montecarlo53.png', 'images/montecarlo/montecarlo54.png', 'images/montecarlo/montecarlo55.png', 'images/montecarlo/montecarlo56.png', 'images/montecarlo/montecarlo57.png', 'images/montecarlo/montecarlo58.png', 'images/montecarlo/montecarlo59.png', 'images/montecarlo/montecarlo60.png'],
	    'width': 480,
	    'delay': 1000,
	    'loopMode': 'loop'
	});
	$('#montecarlo').scianimator('play');
    });
})(jQuery);
